# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean Duncan
email: seaneduncan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a front end developer trying to solve problems on the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seanduncan.net" # the base hostname & protocol for your site
twitter_username: seanevd
github_username:  seanevd
codepen_username: seanevd
dribbble_username: seanevd
github_username: seanevd

# Build settings
markdown: kramdown
exclude: ['README.md', 'package.json', 'node_modules/', '*.log', 'gulpfile.js', 'jekyll/*']
